---
- name: Ensure ZFS datasets for all shares exist
  hosts: proxmox
  become: true
  tasks:
    - name: Ensure ZFS dataset for each share is present
      community.general.zfs:
        name: "{{ zfs_pool }}/{{ item }}"
        state: present
        extra_zfs_properties:
          mountpoint: "/{{ zfs_pool }}/{{ item }}"
      loop: "{{ zfs_datasets }}"
      register: zfs_datasets

    - name: Ensure ZFS datasets are present (idempotent)
      debug:
        msg: "ZFS dataset {{ zfs_pool }}/{{ item.item }} already exists or was created."
      loop: "{{ zfs_datasets.results }}"
