---
# Install Docker on Docker and Pangolin VMs

- name: Install Docker on docker VM
  hosts: docker
  become: true
  roles:
    - geerlingguy.docker
  vars:
    docker_users:
      - stardust

- name: Ensure Docker volumes root directory exists on docker VM
  hosts: docker
  remote_user: stardust
  tasks:
    - name: Create Docker volumes root directory
      ansible.builtin.file:
        path: "{{ docker_volumes_root }}"
        state: directory
        mode: "0755"
        owner: stardust
        group: stardust

- name: Install Docker on pangolin VM
  hosts: pangolin
  become: true
  remote_user: stardust
  roles:
    - geerlingguy.docker
  vars:
    docker_users:
      - stardust

- name: Download Pangolin installer script on pangolin VM
  hosts: pangolin
  remote_user: stardust
  tasks:
    - name: Create pangolin directory
      ansible.builtin.file:
        path: /home/stardust/pangolin
        state: directory
        mode: "0755"
        owner: stardust
        group: stardust
    - name: Download Pangolin installer
      ansible.builtin.get_url:
        url: https://github.com/fosrl/pangolin/releases/latest/download/installer_linux_amd64
        dest: /home/stardust/pangolin/installer
        mode: "0755"
        force: yes
        owner: stardust
        group: stardust
