---
- name: Ensure media directories for anime and non-anime exist
  hosts: proxmox
  become: true
  tasks:
    - name: Create anime/tv directory
      ansible.builtin.file:
        path: "/tank/media/anime/tv"
        state: directory
        owner: 1000
        group: 1000
        mode: "0775"

    - name: Create anime/movies directory
      ansible.builtin.file:
        path: "/tank/media/anime/movies"
        state: directory
        owner: 1000
        group: 1000
        mode: "0775"

    - name: Create non-anime/tv directory
      ansible.builtin.file:
        path: "/tank/media/non-anime/tv"
        state: directory
        owner: 1000
        group: 1000
        mode: "0775"

    - name: Create non-anime/movies directory
      ansible.builtin.file:
        path: "/tank/media/non-anime/movies"
        state: directory
        owner: 1000
        group: 1000
        mode: "0775"
