---
# Deploy Newt agent to Docker VM using Docker Compose

- name: Deploy Newt agent to Docker VM
  hosts: docker
  become: true
  remote_user: stardust
  vars:
    dest_compose_path: /home/stardust/newt/compose.yaml
  tasks:
    - name: Ensure newt directory exists
      ansible.builtin.file:
        path: /home/stardust/newt
        state: directory
        owner: stardust
        group: stardust
        mode: "0755"

    - name: Template Newt Docker Compose file with secrets
      ansible.builtin.template:
        src: ../docker/newt.yaml
        dest: "{{ dest_compose_path }}"
        owner: stardust
        group: stardust
        mode: "0600"

    - name: Deploy Newt agent with Docker Compose v2
      community.docker.docker_compose_v2:
        project_src: /home/stardust/newt
        files:
          - compose.yaml
        state: present
