---
# Deploy Newt agent to Docker VM using Docker Compose

- name: Deploy Newt agent to Docker VM
  hosts: docker
  become: true
  remote_user: stardust
  vars:
    newt_compose_path: /home/stardust/newt/compose.yaml
    newt_compose_content: |
      services:
        newt:
          image: fosrl/newt
          container_name: newt
          restart: unless-stopped
          environment:
            - PANGOLIN_ENDPOINT=https://pangolin.ryanmalonzo.com
            - NEWT_ID={{ lookup('env', 'NEWT_ID') }}
            - NEWT_SECRET={{ lookup('env', 'NEWT_SECRET') }}
  tasks:
    - name: Ensure newt directory exists
      ansible.builtin.file:
        path: /home/stardust/newt
        state: directory
        owner: stardust
        group: stardust
        mode: "0755"

    - name: Copy Newt Docker Compose file
      ansible.builtin.copy:
        dest: "{{ newt_compose_path }}"
        content: "{{ newt_compose_content }}"
        owner: stardust
        group: stardust
        mode: "0644"

    - name: Deploy Newt agent with Docker Compose v2
      community.docker.docker_compose_v2:
        project_src: /home/stardust/newt
        files:
          - compose.yaml
        state: present
      become: true
      become_user: stardust
