---
- name: Mount NFS share in Docker VM
  hosts: docker
  become: true
  vars:
    nfs_server_ip: "{{ proxmox_host_ip }}"
    nfs_export_path: "/tank/media"
    nfs_mount_point: "/mnt/media"
    nfs_mount_opts: "defaults,_netdev"
  tasks:
    - name: Install NFS client package (Debian/Ubuntu)
      ansible.builtin.apt:
        name: nfs-common
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install NFS client package (RHEL/CentOS)
      ansible.builtin.yum:
        name: nfs-utils
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Create mount point directory
      ansible.builtin.file:
        path: "{{ nfs_mount_point }}"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Mount NFS share and ensure persistence
      ansible.posix.mount:
        src: "{{ nfs_server_ip }}:{{ nfs_export_path }}"
        path: "{{ nfs_mount_point }}"
        fstype: nfs
        opts: "{{ nfs_mount_opts }}"
        state: mounted
        boot: true
