---
# Deploy socket proxy to Docker VM using Docker Compose v2

- name: Deploy socket proxy to Docker VM
  hosts: docker
  become: true
  remote_user: stardust
  vars:
    dest_compose_path: /home/stardust/socket-proxy/compose.yaml
  tasks:
    - name: Ensure socket-proxy directory exists
      ansible.builtin.file:
        path: /home/stardust/socket-proxy
        state: directory
        owner: stardust
        group: stardust
        mode: "0755"

    - name: Copy socket proxy Docker Compose file
      ansible.builtin.copy:
        src: ../docker/socket-proxy.yaml
        dest: "{{ dest_compose_path }}"
        owner: stardust
        group: stardust
        mode: "0600"

    - name: Deploy socket proxy stack with Docker Compose v2
      community.docker.docker_compose_v2:
        project_src: /home/stardust/socket-proxy
        files:
          - compose.yaml
        state: present
