services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.10.7
    container_name: jellyfin
    ports:
      - 8096:8096
      # Discovery ports
      - 7359:7359/udp
      - 1900:1900/udp
    volumes:
      - ${DOCKER_APPDATA}/jellyfin:/config
      - ${ZFS_MEDIA}/tvshows:/data/tvshows
      - ${ZFS_MEDIA}/movies:/data/movies
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=https://jellyfin.ryanmalonzo.com
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:5.26.2
    container_name: radarr
    ports:
      - "7878:7878"
    volumes:
      - ${DOCKER_APPDATA}/radarr:/config
      - ${ZFS_MEDIA}/movies:/movies
      - ${ZFS_MEDIA}/downloads:/downloads
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.15
    container_name: sonarr
    ports:
      - "8989:8989"
    volumes:
      - ${DOCKER_APPDATA}/sonarr:/config
      - ${ZFS_MEDIA}/tvshows:/tv
      - ${ZFS_MEDIA}/downloads:/downloads
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped

  profilarr:
    image: santiagosayshey/profilarr:v1.0.1
    container_name: profilarr
    ports:
      - "6868:6868"
    volumes:
      - ${DOCKER_APPDATA}/profilarr:/config
    environment:
      - TZ=${TZ}
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:1.37.0
    container_name: prowlarr
    ports:
      - "9696:9696"
    volumes:
      - ${DOCKER_APPDATA}/prowlarr:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:4.5.2
    container_name: sabnzbd
    ports:
      - "8080:8080"
    volumes:
      - ${DOCKER_APPDATA}/sabnzbd:/config
      - ${ZFS_MEDIA}/incomplete-downloads:/incomplete-downloads
      - ${ZFS_MEDIA}/downloads:/downloads
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    restart: unless-stopped
