services:
  newt:
    image: fosrl/newt:1.3.4
    container_name: newt
    volumes:
      - "socket-proxy:/run/proxy"
    environment:
      - PANGOLIN_ENDPOINT=https://pangolin.ryanmalonzo.com
      - NEWT_ID={{ lookup('env', 'NEWT_ID') }}
      - NEWT_SECRET={{ lookup('env', 'NEWT_SECRET') }}
      - DOCKER_SOCKET=/run/proxy/docker.sock
    networks:
      - socket-proxy
    restart: unless-stopped

volumes:
  socket-proxy:
    external: true

networks:
  socket-proxy:
    external: true
