services:
  socket-proxy:
    image: "11notes/socket-proxy:2.1.3"
    read_only: true
    user: "0:994"
    volumes:
      - "/run/docker.sock:/run/docker.sock:ro"
      - "socket-proxy:/run/proxy"
    restart: unless-stopped

  newt:
    image: fosrl/newt
    container_name: newt
    volumes:
      - "socket-proxy:/run/proxy"
    environment:
      - PANGOLIN_ENDPOINT=https://pangolin.ryanmalonzo.com
      - NEWT_ID={{ lookup('env', 'NEWT_ID') }}
      - NEWT_SECRET={{ lookup('env', 'NEWT_SECRET') }}
      - DOCKER_SOCKET=/run/proxy/docker.sock
    depends_on:
      - socket-proxy
    restart: unless-stopped

volumes:
  socket-proxy:
