services:
  portainer-ee:
    image: "portainer/portainer-ee:lts"
    container_name: portainer
    volumes:
      - "{{ docker_appdata }}/portainer:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "9443:9443"
    restart: unless-stopped
