services:
  socket-proxy:
    image: "11notes/socket-proxy:2.1.3"
    read_only: true
    user: "0:994"
    volumes:
      - "/run/docker.sock:/run/docker.sock:ro"
      - "socket-proxy:/run/proxy"
    restart: unless-stopped

  portainer-ee:
    image: "portainer/portainer-ee:lts"
    container_name: portainer
    volumes:
      - "portainer_data:/data"
      - "socket-proxy:/var/run"
    ports:
      - "9443:9443"
      - "8000:8000"
    depends_on:
      - socket-proxy
    restart: unless-stopped

volumes:
  socket-proxy:
