# Proxmox dynamic inventory for Ansible
plugin: community.general.proxmox
url: '{{ lookup("env", "PROXMOX_VE_ENDPOINT_URL") }}'
user: '{{ lookup("env", "PROXMOX_VE_USERNAME") }}'
password: '{{ lookup("env", "PROXMOX_VE_PASSWORD") }}'
validate_certs: false
want_facts: true
compose:
  ansible_host: proxmox_agent_interfaces[1].get("ip-addresses")[0] | default(proxmox_net0.ip) | ipaddr("address")
  ansible_user: stardust
  ansible_ssh_private_key_file: ../keys/key