---
- name: Install Docker on Proxmox "docker" VM
  hosts: docker
  become: true
  roles:
    - geerlingguy.docker
  vars:
    docker_users:
      - stardust

- name: Install Docker on Scaleway "pangolin" VM
  hosts: pangolin
  become: true
  roles:
    - geerlingguy.docker
  vars:
    docker_users:
      - root
